### ISSUE TITLE
Silence in song

### ISSUE THREAD

**Issue by Mistress-Anna** [GenaBitu/screentunes#2]
It would be nice if it were possible to insert silences in the song, for example with note -1:

"3000": 5,
"3500": -1

**Comment by marekdedic** [comment]
Having the ability to insert silences into the song would be pretty neat, but I didn't come up with a consistent way to implement that. Negative numbers can actually be used to represent notes lower than the base note. I guess you would have to use some hard-coded number way out of possible range, which to me seems to be a bad way to do things. If you have any ideas and/or know jQuery better than me, I would appreciate that.

**Comment by marekdedic** [comment]
Fixed in ad4fcea4df05a2b876166e87de6421bb62befd57
You can now add silence by putting "s" into the JSON
